In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
#link for Jobstreet Singapore for Data Analyst job with salary above SGD4000
URL = "https://www.jobstreet.com.sg/en/job-search/data-analyst-jobs/?salary=4000&salary-max=2147483647"

In [3]:
page = requests.get(URL)

In [4]:
soup = BeautifulSoup(page.text, 'html.parser')

print(soup.prettify())

In [5]:
joblist = []

In [10]:
def extract_from_result(soup): 
    
    for div in soup.find_all("article", attrs={"class": "sx2jih0 sx2jih1 zcydq85u zcydq8h c6ROG_0 _18qlyvc14 _18qlyvc17 zcydq832 zcydq835"}):
        
        company = div.find("span", attrs={"class":"sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1x _18qlyvc1 _18qlyvca"}).text
        
        for locations in div.find_all("span", attrs={"class":"sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1x _18qlyvc3 _18qlyvc7"}):
            locations = div.find("span", attrs={"class":"sx2jih0 zcydq84u zcydq80 iwjz4h0"}).text
        
        #location and salary uses classes with similar name, the different is location contains another class while salary is not
        #code below checks if the class contains a child
        salary = []
        salaries = div.find_all("span", attrs={"class":"sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1x _18qlyvc3 _18qlyvc7"})
        for s in salaries:
            for c in s.children:
                if not hasattr(c,'children'):
                    salary = c
                else:
                    salary = 0
                    
        job = div.find("span", attrs={"class":"sx2jih0"}).text
        
        d = div.find("ul", attrs={"class":"sx2jih0 sx2jih3 h6p8rp0 h6p8rp5"}).text
        
        #for desc in d:
        #    desc = div.find_all("span", attrs={"class":"sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1x _18qlyvc1 _1d0g9qk4 _18qlyvc8"})
        #    for d in desc:
        #        for c in d.children:
        #            desces = c
        
        #desc = div.find_all("span", attrs={"class":"sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1x _18qlyvc1 _1d0g9qk4 _18qlyvc8"})
        #for d in desc:
        #    for c in d.children:
        #        desces = c
                
        jobs = {
            "company" : company,
            "place" : locations,
            "payment" : salary,
            "role" : job,
            "descriptions" : d
        }
        
        joblist.append(jobs)
        
        #print(d)
        
    return

results = soup.find_all(name="article", attrs={"class":"sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1x _18qlyvc3 _18qlyvc7"})

results

In [7]:
extract_from_result(soup)

In [8]:
print(joblist)

[{'company': 'Pacific Life Re Limited', 'place': 'Central', 'payment': 0, 'role': 'Data Management Analyst', 'descriptions': 'Full flexi working policyVery friendly and supportive working environmentGood training and development opportunities'}, {'company': 'Phillip Securities Pte Ltd', 'place': 'East - Others', 'payment': 0, 'role': 'Data Analyst', 'descriptions': 'Staff EngagementLearning & Development'}, {'company': 'AIA SINGAPORE PRIVATE LIMITED', 'place': 'Tampines', 'payment': 0, 'role': 'Business Analyst (JR-21140)', 'descriptions': ''}, {'company': 'Rentokil Initial Singapore Pte Ltd', 'place': 'East', 'payment': 0, 'role': 'Financial Data Business Analyst - Tai Seng', 'descriptions': ''}, {'company': 'MVL Foundation Pte Ltd - TADA Mobility', 'place': 'East - Others', 'payment': 'SGD\xa06K - 12K monthly', 'role': 'Lead/Senior Data Analyst', 'descriptions': ''}, {'company': 'NTUC LearningHub Pte Ltd', 'place': 'Central - Others', 'payment': 0, 'role': 'Data Engineer', 'descriptions': ''}, {'company': 'Ifun Singapore Pte. Ltd.', 'place': 'West', 'payment': 0, 'role': 'Data Analysis Manager, Casual Games', 'descriptions': ''}, {'company': 'Phillip Securities Pte Ltd', 'place': 'East', 'payment': 'SGD\xa05.5K - 7.5K monthly', 'role': 'Data Scientist', 'descriptions': 'Staff EngagementLearning & Development'}, {'company': 'iZeno Pte Ltd', 'place': 'Toa Payoh', 'payment': 'SGD\xa04.5K - 6.5K monthly', 'role': 'Analytics Consultant / Data Engineer / Business Intelligence', 'descriptions': 'Hybrid work modelNew and exciting technologiesAdvanced training opportunities'}, {'company': 'DSBJ PTE. LTD.', 'place': 'Bishan', 'payment': 0, 'role': 'Data Architect', 'descriptions': 'Newly created roleCompetitive benefits packagePositive work environment'}, {'company': 'VGS Asia', 'place': 'Central', 'payment': 0, 'role': 'Business Analyst', 'descriptions': 'Attractive & competitive salaryTeamwork mindsetCareer Progression'}, {'company': 'TRUE YOGA â€¢ TRUE FITNESS', 'place': 'Central', 'payment': 'SGD\xa03.5K - 5.5K monthly', 'role': 'System Analyst (ERP)', 'descriptions': 'Attractive remuneration packageFun working environment'}, {'company': 'AIA SINGAPORE PRIVATE LIMITED', 'place': 'Singapore', 'payment': 0, 'role': 'Business Analyst, Claims System (JR-19794)', 'descriptions': ''}, {'company': 'Federal Express (S) Pte Ltd', 'place': 'Changi', 'payment': 'SGD\xa04.1K - 7K monthly', 'role': 'Marketing Analyst', 'descriptions': ''}, {'company': 'KAPTECH CONSULTING PTE LTD(Weaver Singapore)', 'place': 'Downtown Core', 'payment': 'SGD\xa03.6K - 6K monthly', 'role': 'Tecnology Business Analyst', 'descriptions': ''}, {'company': 'Linden Shore LLC', 'place': 'Downtown Core', 'payment': 'SGD\xa03.5K - 7K monthly', 'role': 'Trading Analyst', 'descriptions': 'Competitive compensation package with performance-based bonusCollaborative working environment with talented professionalsTremendous opportunity for learning and professional growth'}, {'company': 'NTT Data Business Solutions Singapore Pte Ltd', 'place': 'Bishan', 'payment': 0, 'role': 'Consultant (BI & Data Management)', 'descriptions': 'Inspire people to growDiversity, inclusion and sense of belongingPassionate, unpretentious and together'}, {'company': 'Suez Singapore', 'place': 'West - Others', 'payment': 0, 'role': 'Junior Data Analyst / Scientist', 'descriptions': ''}, {'company': 'Spring Professional (Singapore) Pte Ltd', 'place': 'Central', 'payment': 'SGD\xa04K - 5.5K monthly', 'role': 'Data Analyst - Data Tech', 'descriptions': ''}, {'company': 'Michael Page', 'place': 'North-East', 'payment': 0, 'role': 'Data Analyst', 'descriptions': ''}, {'company': 'Aviva Financial Advisers Pte Ltd', 'place': 'Central', 'payment': 0, 'role': 'Data Analyst', 'descriptions': ''}, {'company': 'Titansoft Pte Ltd', 'place': 'Outram', 'payment': 'SGD\xa04.5K - 6.8K monthly', 'role': 'Data Analyst', 'descriptions': 'Continuous learning opportunitiesFlexible and open working environmentAttractive compensation and benefits package'}, {'company': 'D L Resources Pte Ltd', 'place': 'Singapore', 'payment': 0, 'role': 'Data Analyst', 'descriptions': ''}, {'company': 'Changi General Hospital', 'place': 'East', 'payment': 0, 'role': 'Analyst, Data Management & Informatics', 'descriptions': ''}, {'company': 'FCM Travel Solutions Asia', 'place': 'Downtown Core', 'payment': 0, 'role': 'Data Analyst', 'descriptions': 'Regional exposureFun and open work environmentGlobal travel management company'}, {'company': 'Spring Professional (Singapore) Pte Ltd', 'place': 'Central', 'payment': 0, 'role': 'Data Analyst - Digital Marketing', 'descriptions': ''}, {'company': 'Raffles Institution', 'place': 'Bishan', 'payment': 'SGD\xa02.7K - 4.5K monthly', 'role': 'Systems Analyst', 'descriptions': 'Work-life BalancePositive working environmentAttractive overall package'}, {'company': 'Achieve Career Consultant Pte Ltd', 'place': 'Central', 'payment': 'SGD\xa04K - 5K monthly', 'role': 'Data Analyst - Data Collection / Oil & Gas / MNC', 'descriptions': ''}, {'company': 'Karooooo Management Company Pte Ltd', 'place': 'Paya Lebar', 'payment': 'SGD\xa04K - 5.6K monthly', 'role': 'Data Analyst (Business Intelligence & Analytics)', 'descriptions': ''}, {'company': 'Ministry of Health', 'place': 'Singapore', 'payment': 0, 'role': 'Data Analyst (Data Management Unit, Contact Tracing Centre) (1-Year Contract)', 'descriptions': ''}]

In [9]:
df = pd.DataFrame(joblist)
df

,company,place,payment,role,descriptions
0,Pacific Life Re Limited,Central,0,Data Management Analyst,Full flexi working policyVery friendly and sup...
1,Phillip Securities Pte Ltd,East - Others,0,Data Analyst,Staff EngagementLearning & Development
2,AIA SINGAPORE PRIVATE LIMITED,Tampines,0,Business Analyst (JR-21140),
3,Rentokil Initial Singapore Pte Ltd,East,0,Financial Data Business Analyst - Tai Seng,
4,MVL Foundation Pte Ltd - TADA Mobility,East - Others,SGDÂ 6K - 12K monthly,Lead/Senior Data Analyst,
5,NTUC LearningHub Pte Ltd,Central - Others,0,Data Engineer,
6,Ifun Singapore Pte. Ltd.,West,0,"Data Analysis Manager, Casual Games",
7,Phillip Securities Pte Ltd,East,SGDÂ 5.5K - 7.5K monthly,Data Scientist,Staff EngagementLearning & Development
8,iZeno Pte Ltd,Toa Payoh,SGDÂ 4.5K - 6.5K monthly,Analytics Consultant / Data Engineer / Busines...,Hybrid work modelNew and exciting technologies...
9,DSBJ PTE. LTD.,Bishan,0,Data Architect,Newly created roleCompetitive benefits package...
10,VGS Asia,Central,0,Business Analyst,Attractive & competitive salaryTeamwork mindse...
11,TRUE YOGA â€¢ TRUE FITNESS,Central,SGDÂ 3.5K - 5.5K monthly,System Analyst (ERP),Attractive remuneration packageFun working env...
12,AIA SINGAPORE PRIVATE LIMITED,Singapore,0,"Business Analyst, Claims System (JR-19794)",
13,Federal Express (S) Pte Ltd,Changi,SGDÂ 4.1K - 7K monthly,Marketing Analyst,
14,KAPTECH CONSULTING PTE LTD(Weaver Singapore),Downtown Core,SGDÂ 3.6K - 6K monthly,Tecnology Business Analyst,
15,Linden Shore LLC,Downtown Core,SGDÂ 3.5K - 7K monthly,Trading Analyst,Competitive compensation package with performa...
16,NTT Data Business Solutions Singapore Pte Ltd,Bishan,0,Consultant (BI & Data Management),"Inspire people to growDiversity, inclusion and..."
17,Suez Singapore,West - Others,0,Junior Data Analyst / Scientist,
18,Spring Professional (Singapore) Pte Ltd,Central,SGDÂ 4K - 5.5K monthly,Data Analyst - Data Tech,
19,Michael Page,North-East,0,Data Analyst,
20,Aviva Financial Advisers Pte Ltd,Central,0,Data Analyst,
21,Titansoft Pte Ltd,Outram,SGDÂ 4.5K - 6.8K monthly,Data Analyst,Continuous learning opportunitiesFlexible and ...
22,D L Resources Pte Ltd,Singapore,0,Data Analyst,
23,Changi General Hospital,East,0,"Analyst, Data Management & Informatics",
24,FCM Travel Solutions Asia,Downtown Core,0,Data Analyst,Regional exposureFun and open work environment...
25,Spring Professional (Singapore) Pte Ltd,Central,0,Data Analyst - Digital Marketing,
26,Raffles Institution,Bishan,SGDÂ 2.7K - 4.5K monthly,Systems Analyst,Work-life BalancePositive working environmentA...
27,Achieve Career Consultant Pte Ltd,Central,SGDÂ 4K - 5K monthly,Data Analyst - Data Collection / Oil & Gas / MNC,
28,Karooooo Management Company Pte Ltd,Paya Lebar,SGDÂ 4K - 5.6K monthly,Data Analyst (Business Intelligence & Analytics),
29,Ministry of Health,Singapore,0,"Data Analyst (Data Management Unit, Contact Tr...",